//go:build !ignore_autogenerated

/*
This file was generated with "make generate-deepcopy".
*/

// Code generated by controller-gen. DO NOT EDIT.

package v2

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdditionalMount) DeepCopyInto(out *AdditionalMount) {
	*out = *in
	if in.Subfolder != nil {
		in, out := &in.Subfolder, &out.Subfolder
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdditionalMount.
func (in *AdditionalMount) DeepCopy() *AdditionalMount {
	if in == nil {
		return nil
	}
	out := new(AdditionalMount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Blueprint) DeepCopyInto(out *Blueprint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(BlueprintStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Blueprint.
func (in *Blueprint) DeepCopy() *Blueprint {
	if in == nil {
		return nil
	}
	out := new(Blueprint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Blueprint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlueprintList) DeepCopyInto(out *BlueprintList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Blueprint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlueprintList.
func (in *BlueprintList) DeepCopy() *BlueprintList {
	if in == nil {
		return nil
	}
	out := new(BlueprintList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BlueprintList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlueprintManifest) DeepCopyInto(out *BlueprintManifest) {
	*out = *in
	if in.Dogus != nil {
		in, out := &in.Dogus, &out.Dogus
		*out = make([]Dogu, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(Config)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlueprintManifest.
func (in *BlueprintManifest) DeepCopy() *BlueprintManifest {
	if in == nil {
		return nil
	}
	out := new(BlueprintManifest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlueprintMask) DeepCopyInto(out *BlueprintMask) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(BlueprintMaskStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlueprintMask.
func (in *BlueprintMask) DeepCopy() *BlueprintMask {
	if in == nil {
		return nil
	}
	out := new(BlueprintMask)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BlueprintMask) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlueprintMaskList) DeepCopyInto(out *BlueprintMaskList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BlueprintMask, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlueprintMaskList.
func (in *BlueprintMaskList) DeepCopy() *BlueprintMaskList {
	if in == nil {
		return nil
	}
	out := new(BlueprintMaskList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BlueprintMaskList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlueprintMaskManifest) DeepCopyInto(out *BlueprintMaskManifest) {
	*out = *in
	if in.Dogus != nil {
		in, out := &in.Dogus, &out.Dogus
		*out = make([]MaskDogu, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlueprintMaskManifest.
func (in *BlueprintMaskManifest) DeepCopy() *BlueprintMaskManifest {
	if in == nil {
		return nil
	}
	out := new(BlueprintMaskManifest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlueprintMaskRef) DeepCopyInto(out *BlueprintMaskRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlueprintMaskRef.
func (in *BlueprintMaskRef) DeepCopy() *BlueprintMaskRef {
	if in == nil {
		return nil
	}
	out := new(BlueprintMaskRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlueprintMaskSpec) DeepCopyInto(out *BlueprintMaskSpec) {
	*out = *in
	if in.BlueprintMaskManifest != nil {
		in, out := &in.BlueprintMaskManifest, &out.BlueprintMaskManifest
		*out = new(BlueprintMaskManifest)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlueprintMaskSpec.
func (in *BlueprintMaskSpec) DeepCopy() *BlueprintMaskSpec {
	if in == nil {
		return nil
	}
	out := new(BlueprintMaskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlueprintMaskStatus) DeepCopyInto(out *BlueprintMaskStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlueprintMaskStatus.
func (in *BlueprintMaskStatus) DeepCopy() *BlueprintMaskStatus {
	if in == nil {
		return nil
	}
	out := new(BlueprintMaskStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlueprintSpec) DeepCopyInto(out *BlueprintSpec) {
	*out = *in
	in.Blueprint.DeepCopyInto(&out.Blueprint)
	if in.BlueprintMask != nil {
		in, out := &in.BlueprintMask, &out.BlueprintMask
		*out = new(BlueprintMaskManifest)
		(*in).DeepCopyInto(*out)
	}
	if in.BlueprintMaskRef != nil {
		in, out := &in.BlueprintMaskRef, &out.BlueprintMaskRef
		*out = new(BlueprintMaskRef)
		**out = **in
	}
	if in.IgnoreDoguHealth != nil {
		in, out := &in.IgnoreDoguHealth, &out.IgnoreDoguHealth
		*out = new(bool)
		**out = **in
	}
	if in.AllowDoguNamespaceSwitch != nil {
		in, out := &in.AllowDoguNamespaceSwitch, &out.AllowDoguNamespaceSwitch
		*out = new(bool)
		**out = **in
	}
	if in.Stopped != nil {
		in, out := &in.Stopped, &out.Stopped
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlueprintSpec.
func (in *BlueprintSpec) DeepCopy() *BlueprintSpec {
	if in == nil {
		return nil
	}
	out := new(BlueprintSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlueprintStatus) DeepCopyInto(out *BlueprintStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EffectiveBlueprint != nil {
		in, out := &in.EffectiveBlueprint, &out.EffectiveBlueprint
		*out = new(BlueprintManifest)
		(*in).DeepCopyInto(*out)
	}
	if in.StateDiff != nil {
		in, out := &in.StateDiff, &out.StateDiff
		*out = new(StateDiff)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlueprintStatus.
func (in *BlueprintStatus) DeepCopy() *BlueprintStatus {
	if in == nil {
		return nil
	}
	out := new(BlueprintStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CombinedDoguConfigDiff) DeepCopyInto(out *CombinedDoguConfigDiff) {
	*out = *in
	if in.DoguConfigDiff != nil {
		in, out := &in.DoguConfigDiff, &out.DoguConfigDiff
		*out = make(DoguConfigDiff, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SensitiveDoguConfigDiff != nil {
		in, out := &in.SensitiveDoguConfigDiff, &out.SensitiveDoguConfigDiff
		*out = make(DoguConfigDiff, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CombinedDoguConfigDiff.
func (in *CombinedDoguConfigDiff) DeepCopy() *CombinedDoguConfigDiff {
	if in == nil {
		return nil
	}
	out := new(CombinedDoguConfigDiff)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Config) DeepCopyInto(out *Config) {
	*out = *in
	if in.Dogus != nil {
		in, out := &in.Dogus, &out.Dogus
		*out = make(map[string][]ConfigEntry, len(*in))
		for key, val := range *in {
			var outVal []ConfigEntry
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]ConfigEntry, len(*in))
				for i := range *in {
					(*in)[i].DeepCopyInto(&(*out)[i])
				}
			}
			(*out)[key] = outVal
		}
	}
	if in.Global != nil {
		in, out := &in.Global, &out.Global
		*out = make([]ConfigEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Config.
func (in *Config) DeepCopy() *Config {
	if in == nil {
		return nil
	}
	out := new(Config)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in ConfigDiff) DeepCopyInto(out *ConfigDiff) {
	{
		in := &in
		*out = make(ConfigDiff, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigDiff.
func (in ConfigDiff) DeepCopy() ConfigDiff {
	if in == nil {
		return nil
	}
	out := new(ConfigDiff)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigEntry) DeepCopyInto(out *ConfigEntry) {
	*out = *in
	if in.Absent != nil {
		in, out := &in.Absent, &out.Absent
		*out = new(bool)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
	if in.Sensitive != nil {
		in, out := &in.Sensitive, &out.Sensitive
		*out = new(bool)
		**out = **in
	}
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(SecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigEntry.
func (in *ConfigEntry) DeepCopy() *ConfigEntry {
	if in == nil {
		return nil
	}
	out := new(ConfigEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigEntryDiff) DeepCopyInto(out *ConfigEntryDiff) {
	*out = *in
	in.Actual.DeepCopyInto(&out.Actual)
	in.Expected.DeepCopyInto(&out.Expected)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigEntryDiff.
func (in *ConfigEntryDiff) DeepCopy() *ConfigEntryDiff {
	if in == nil {
		return nil
	}
	out := new(ConfigEntryDiff)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigValueState) DeepCopyInto(out *ConfigValueState) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigValueState.
func (in *ConfigValueState) DeepCopy() *ConfigValueState {
	if in == nil {
		return nil
	}
	out := new(ConfigValueState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in DoguConfigDiff) DeepCopyInto(out *DoguConfigDiff) {
	{
		in := &in
		*out = make(DoguConfigDiff, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DoguConfigDiff.
func (in DoguConfigDiff) DeepCopy() DoguConfigDiff {
	if in == nil {
		return nil
	}
	out := new(DoguConfigDiff)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DoguConfigValueState) DeepCopyInto(out *DoguConfigValueState) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DoguConfigValueState.
func (in *DoguConfigValueState) DeepCopy() *DoguConfigValueState {
	if in == nil {
		return nil
	}
	out := new(DoguConfigValueState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DoguDiff) DeepCopyInto(out *DoguDiff) {
	*out = *in
	in.Actual.DeepCopyInto(&out.Actual)
	in.Expected.DeepCopyInto(&out.Expected)
	if in.NeededActions != nil {
		in, out := &in.NeededActions, &out.NeededActions
		*out = make([]DoguAction, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DoguDiff.
func (in *DoguDiff) DeepCopy() *DoguDiff {
	if in == nil {
		return nil
	}
	out := new(DoguDiff)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DoguDiffState) DeepCopyInto(out *DoguDiffState) {
	*out = *in
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
	if in.ResourceConfig != nil {
		in, out := &in.ResourceConfig, &out.ResourceConfig
		*out = new(ResourceConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ReverseProxyConfig != nil {
		in, out := &in.ReverseProxyConfig, &out.ReverseProxyConfig
		*out = new(ReverseProxyConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.AdditionalMounts != nil {
		in, out := &in.AdditionalMounts, &out.AdditionalMounts
		*out = make([]AdditionalMount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DoguDiffState.
func (in *DoguDiffState) DeepCopy() *DoguDiffState {
	if in == nil {
		return nil
	}
	out := new(DoguDiffState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in GlobalConfigDiff) DeepCopyInto(out *GlobalConfigDiff) {
	{
		in := &in
		*out = make(GlobalConfigDiff, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalConfigDiff.
func (in GlobalConfigDiff) DeepCopy() GlobalConfigDiff {
	if in == nil {
		return nil
	}
	out := new(GlobalConfigDiff)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalConfigValueState) DeepCopyInto(out *GlobalConfigValueState) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalConfigValueState.
func (in *GlobalConfigValueState) DeepCopy() *GlobalConfigValueState {
	if in == nil {
		return nil
	}
	out := new(GlobalConfigValueState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaskDogu) DeepCopyInto(out *MaskDogu) {
	*out = *in
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
	if in.Absent != nil {
		in, out := &in.Absent, &out.Absent
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaskDogu.
func (in *MaskDogu) DeepCopy() *MaskDogu {
	if in == nil {
		return nil
	}
	out := new(MaskDogu)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformConfig) DeepCopyInto(out *PlatformConfig) {
	*out = *in
	if in.ResourceConfig != nil {
		in, out := &in.ResourceConfig, &out.ResourceConfig
		*out = new(ResourceConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ReverseProxyConfig != nil {
		in, out := &in.ReverseProxyConfig, &out.ReverseProxyConfig
		*out = new(ReverseProxyConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.AdditionalMountsConfig != nil {
		in, out := &in.AdditionalMountsConfig, &out.AdditionalMountsConfig
		*out = make([]AdditionalMount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformConfig.
func (in *PlatformConfig) DeepCopy() *PlatformConfig {
	if in == nil {
		return nil
	}
	out := new(PlatformConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceConfig) DeepCopyInto(out *ResourceConfig) {
	*out = *in
	if in.MinVolumeSize != nil {
		in, out := &in.MinVolumeSize, &out.MinVolumeSize
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceConfig.
func (in *ResourceConfig) DeepCopy() *ResourceConfig {
	if in == nil {
		return nil
	}
	out := new(ResourceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReverseProxyConfig) DeepCopyInto(out *ReverseProxyConfig) {
	*out = *in
	if in.MaxBodySize != nil {
		in, out := &in.MaxBodySize, &out.MaxBodySize
		*out = new(string)
		**out = **in
	}
	if in.RewriteTarget != nil {
		in, out := &in.RewriteTarget, &out.RewriteTarget
		*out = new(string)
		**out = **in
	}
	if in.AdditionalConfig != nil {
		in, out := &in.AdditionalConfig, &out.AdditionalConfig
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReverseProxyConfig.
func (in *ReverseProxyConfig) DeepCopy() *ReverseProxyConfig {
	if in == nil {
		return nil
	}
	out := new(ReverseProxyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StateDiff) DeepCopyInto(out *StateDiff) {
	*out = *in
	if in.DoguDiffs != nil {
		in, out := &in.DoguDiffs, &out.DoguDiffs
		*out = make(map[string]DoguDiff, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.DoguConfigDiffs != nil {
		in, out := &in.DoguConfigDiffs, &out.DoguConfigDiffs
		*out = make(map[string]CombinedDoguConfigDiff, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.GlobalConfigDiff != nil {
		in, out := &in.GlobalConfigDiff, &out.GlobalConfigDiff
		*out = make(GlobalConfigDiff, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StateDiff.
func (in *StateDiff) DeepCopy() *StateDiff {
	if in == nil {
		return nil
	}
	out := new(StateDiff)
	in.DeepCopyInto(out)
	return out
}
